
//  ---------- INLCUDED BLOCK: MUX2_32  ---------- 
module MUX2_32 (
  input [31:0] A, 
  input [31:0] B, 
  input S, 
  output [31:0] Z
);
  assign Z = (S) ? B : A;
endmodule



//  ---------- INLCUDED BLOCK: ALU  ---------- 
module ALU (
    input signed [31:0] i_A,
    input signed [31:0] i_B,
  	input [2:0] i_Sel,
    output reg signed [31:0] o_Q
);
    localparam c_ALU_OP_ADD = 3'b000;
	localparam c_ALU_OP_SUB = 3'b001;
	localparam c_ALU_OP_AND = 3'b010;
	localparam c_ALU_OP_OR 	= 3'b011;
	localparam c_ALU_OP_XOR	= 3'b100;
  
    always @ (*) begin
        case (i_Sel)
            c_ALU_OP_SUB:     o_Q = i_A - i_B;
            c_ALU_OP_AND:     o_Q = i_A & i_B;
            c_ALU_OP_OR:      o_Q = i_A | i_B;
            c_ALU_OP_XOR:     o_Q = i_A ^ i_B;
            default:          o_Q = i_A + i_B;
        endcase
    end
endmodule


// Automatically generated by ChipInventor Cloud EDA Tool - 3.15
// Careful: this file (hdl.v) will be automatically replaced
// when you ask tool to generate top Verilog code by clicking
// at BLOCKS button.

module top (

  input wire [2:0] i_ALU_OP,
  input wire [31:0] i_register_RS_1,
  input wire [31:0] i_register_RS_2,
  input wire [31:0] I_pc_output,
  input wire [31:0] i_immediate,
  input wire i_B_sel,
  input wire i_A_Sel,
  output wire [31:0] o_Q

);

//Internal Wires
 wire [31:0] w_1;
 wire [31:0] w_2;

//Instances of Modules
ALU blk2109_3 (
         .i_Sel (i_ALU_OP [2:0]),
         .o_Q (o_Q [31:0]),
         .i_A (w_1),
         .i_B (w_2)
     );

MUX2_32 blk1779_4 (
         .A (i_register_RS_2 [31:0]),
         .B (i_immediate [31:0]),
         .S (i_B_sel),
         .Z (w_2)
     );

MUX2_32 blk1779_5 (
         .A (i_register_RS_1 [31:0]),
         .B (I_pc_output [31:0]),
         .S (i_A_Sel),
         .Z (w_1)
     );


endmodule
